var fs = require('fs');
var multer  = require('multer');
var upload = multer({ dest: 'uploads/' }); //setting the default folder for multer
const express = require('express')
const app = express()
app.get('/', (req, res) => res.send('Hello World!'))

app.listen(3000, () => console.log('Example app listening on port 3000!'))
//other imports and code will go here
app.post('/upload',upload.single('fileData'), (req, res,next) => {
  console.log('upload');
  console.log(req.file);
  console.log(req.body);
  //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
//   fs.readFile(req.file.path,(err, contents)=> {
//    if (err) {
//    console.log('Error: ', err);
//   }else{
//    console.log('File contents ',contents);
//   }
//  });
});






